[package]
name          = "sqlx-d1"
version       = "0.1.0"
edition       = "2024"
authors       = ["kanarus <kanarus786@gmail.com>"]
documentation = "https://docs.rs/sqlx-d1"
homepage      = "https://crates.io/crates/sqlx-d1"
repository    = "https://github.com/ohkami-rs/sqlx-d1"
readme        = "README.md"
license       = "MIT"
description   = "SQLx for Cloudflare D1"
keywords      = ["cloudflare", "d1", "sqlx", "database", "db"]
categories    = ["database", "asynchronous", "wasm", "rust-patterns", "network-programming"]

[features]
# DEBUG
# default = ["json", "uuid"]

json = ["sqlx-core/json", "dep:serde"]
uuid = ["sqlx-core/uuid", "dep:uuid"]

# time not implemented on this platform

[dependencies]
# core dependencies
sqlx-core    = "0.8"
worker       = { version = "0.5", features = ["d1"] }
futures-core = { version = "0.3", default-features = false }
futures-util = { version = "0.3", default-features = false }
log          = "0.4" # required for `sqlx_core::connection::ConnectOptions`

# optional dependencies
serde  = { optional = true, version = "1.0" }
uuid   = { optional = true, version = "1.14" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx-sqlite = { version = "0.8", features = ["bundled"] }